default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: projekt
  password: mmje091929

development:
  <<: *default
  adapter: postgresql
  database: projekt_development
  username: projekt
  password: mmje091929

test:
  <<: *default
  adapter: postgresql
  database: projekt_test
  username: projekt
  password: mmje091929

production:
  <<: *default
  adapter: postgresql
  database: projekt_production
  username: projekt
  password: <%=  ENV['PROJEKT_PASSWORD'] %>

